### ISSUE TITLE
view Retained timestamp

### ISSUE THREAD

**Issue by arturxedex128** [EdJoPaTo/mqttui#120]
Hi,

First of: Thx for your work on mqttui!

Second: can you plz provide the timestamp on retained msg's ... timestamp is missing if message is retained.

something like that:

OLD:

RETAINED     AtLeastOnce disconnected
8:07:20.495 AtLeastOnce connected
8:07:25.976 AtLeastOnce disconnected
8:07:27.543 AtLeastOnce connected
8:07:34.260 AtLeastOnce disconnected 

NEW:

8:03:20:345 Re AtLeastOnce disconnected
8:07:20.495       AtLeastOnce connected
8:07:25.976       AtLeastOnce disconnected
8:07:27.543       AtLeastOnce connected
8:07:34.260       AtLeastOnce disconnected 

greets
Artur

**Comment by EdJoPaTo** [comment]
It is not possible to know when a message was retained. The broker keeps the last retained message for a topic which can be minutes or days old. MQTT doesn't provide this information so only the startup time could be provided which is certainly wrong.
Would be nice to know when the retained message was sent but with MQTT its sadly not possible.
