### ISSUE TITLE
Viewing Images

### ISSUE THREAD

**Issue by arturxedex128** [EdJoPaTo/mqttui#121]
Hi,

can you provide a possiblity to view images with https://github.com/ueber-devel/ueberzug?

that would be nice.

greets
Artur

**Comment by EdJoPaTo** [comment]
Im not sure how common images via MQTT are.

The big downside would be additional payload analysing logic required. One of the biggest performance consumers currently is the payload content check checking for a Unicode string inside of the byte payload. Doing even more there would result in a less fast program which will be notable on brokers with many messages going on.
