### ISSUE TITLE
Scrolling in History

### ISSUE THREAD

**Issue by arturxedex128** [EdJoPaTo/mqttui#122]
Hi,

can you provide scrolling in the History-TAB?

the History entries to view are depending on the window-size/terminal-size. Just need a possiblity to scroll in the history

**Comment by EdJoPaTo** [comment]
Basically the same idea as came up [here](https://github.com/EdJoPaTo/mqttui/issues/103#issuecomment-1374492316). I'll leave this open as a dedicated issue for this idea as I still like it.

**Comment by EdJoPaTo** [comment]
Scrolling and selecting entries in [v0.20.0](https://github.com/EdJoPaTo/mqttui/releases/tag/v0.20.0) is possible now :sparkles:
