### ISSUE TITLE
Allow full view of a large (eg JSON) historical item selected from the history tab

### ISSUE THREAD

**Issue by sshaikh** [EdJoPaTo/mqttui#133]
Although I can see the history of a topic coming in, it's very difficult to retrieve that information, particularly as mqttui "helpfully" reformats json as a tree ;).

If the UI won't allow us to view the full content of a message in history, perhaps allow a way to copy it out?

**Comment by EdJoPaTo** [comment]
Hey! Thank you for thinking about improvements!

The reformatting of JSON should only occur in the Payload Box in the top right?
There is the idea floating around about selecting a message from the history to show its full contents in to top right payload box (see #122).
Would that work for you?

Copying stuff into the system payload from the terminal is a bit tricky if I remember that right. Maybe there is a useful rust crate to do something like that which already handles the difficult parts.

**Comment by sshaikh** [comment]
Correct, it only formats in the payload box (my point being that it was still difficult to extract it wholesale).

Having a view for selected history entry would be exactly what I'm requesting!

**Comment by EdJoPaTo** [comment]
Then #122 is relevant for that part of what you would need. The other part is to display JSON plainly to allow for easier copying? Maybe we should update the title of this Issue then to remember it easier.

Thanks for your input!

**Comment by sshaikh** [comment]
To be fair although I would appreciate (vertical, I presume?) scrolling, I'm not sure how that alone solves the issue of being able to view the actual historical item fully.

I'll try to give a more appropriate description though.

**Comment by EdJoPaTo** [comment]
Copying data out is another idea that would be interesting. I opened #159 for this.

Selecting an entry from the history table is possible with the just released [v0.20.0](https://github.com/EdJoPaTo/mqttui/releases/tag/v0.20.0) now :sparkles:
