### ISSUE TITLE
copy data

### ISSUE THREAD

**Issue by sj13824803000** [EdJoPaTo/mqttui#136]
How to copy any to the clipboard, such as topic, content, etc.

**Comment by EdJoPaTo** [comment]
mqttui uses the Terminal Alt Mode. Also mouse and keyboard inputs are captured. Most Terminals provide a way to let the running process not capture mouse/keyboard by pressing Shift for example. Personally I press shift, double click the topic and then copy it via Ctrl + Shift + C.

**Comment by sj13824803000** [comment]
> mqttui uses the Terminal Alt Mode. Also mouse and keyboard inputs are captured. Most Terminals provide a way to let the running process not capture mouse/keyboard by pressing Shift for example. Personally I press shift, double click the topic and then copy it via Ctrl + Shift + C.

thanks
