### ISSUE TITLE
Private key error

### ISSUE THREAD

**Issue by kenwoodberry** [EdJoPaTo/mqttui#140]
I'm using MQTT over TLS, and I can get other MQTT clients to work successfully with the PKI I've set up, but with mqttui I always get this error:

"Error: Private key file must contain exactly one key"

The private key file in question definitely only contains one key.

Thanks.

Ken

**Comment by boxmein** [comment]
Hi, I think the key is not a PKCS#8 formatted private key. I built myself a test binary using the same code, and saw these results:

* This key works: `openssl req -nodes -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname"`
* This key also works: `openssl ecparam -name prime256v1 -genkey -noout -out eckey.pem`
* This key does not work: `ssh-keygen -t rsa -b 4096`
* This key also does not work: `ssh-keygen -t ecdsa`
