### ISSUE TITLE
Binary payload

### ISSUE THREAD

**Issue by alex007sirois** [EdJoPaTo/mqttui#141]
When having a binary payload (ex: protobuf), I get the following message in the payload window:

> Payload (Bytes: 93)
invalid utf-8 sequence of 1 bytes from index 81

It would be nice if it simply printed an hex representation of the payload:

> Payload (Bytes: 4)
01 AA FF 32

Although I guess you would need to be wary about too big payload.

**Comment by EdJoPaTo** [comment]
Displaying smaller binary payload as hex would be indeed interesting!

For simplicity a hardcoded max size for this seems smart to prevent huge payloads to fill up the history.

**Comment by EdJoPaTo** [comment]
I just released [v0.20.0](https://github.com/EdJoPaTo/mqttui/releases/tag/v0.20.0) which contains a binary payload viewer and can pipe them to stdout with `mqttui read-one`.
Also, the interactive view has `--payload-size-limit` now for limiting the max size which is stored. Payloads bigger than that are truncated.

Thanks again for suggesting this!
