### ISSUE TITLE
Self-signed certificate triggers UnsupportedCertVersion error

### ISSUE THREAD

**Issue by lanceybp** [EdJoPaTo/mqttui#142]
Connecting to a `mqtts` test broker exposing a self-signed certificate triggers the following error:
```
Error: TLS: I/O: invalid peer certificate: Other(UnsupportedCertVersion)

Caused by:
    0: I/O: invalid peer certificate: Other(UnsupportedCertVersion)
    1: invalid peer certificate: Other(UnsupportedCertVersion)
```

MQTT server certificate has been generated following this guide:
https://mariadb.com/docs/xpand/security/data-in-transit-encryption/create-self-signed-certificates-keys-openssl/

Using the `--insecure` flag does not bypass the error

**Comment by EdJoPaTo** [comment]
Personally I haven't used MQTT over TLS yet. (Maybe I should try sometimes when I have more time…)

From the error it looks like the versions are different ones from what rustls currently supports. Maybe newer dependencies of mqttui might solve this but it's only dumb first guess.
Other than that I am not sure what might be a good way to solve this. To me it looks like the certificate is just too far away from being understood by rustls so it's not insecure, it's unsupported. I just don't really know why.

@boxmein Do you have any thoughts on this?

**Comment by lanceybp** [comment]
It seems that `rusttls` only supports x509 v3 self-signed certificates (not default v1 ones)  
cf. https://github.com/rustls/rustls/issues/124#issuecomment-338108318

Using the following guide I generated a v3 certificate and `mqttui` is now happy
cf. https://gist.github.com/akrisiun/7440d84138c91ca23d7a33921053659f#file-gistfile1-md

Command return without the `--insecure` flag is now:  
```
Error: TLS: I/O: invalid peer certificate: UnknownIssuer

Caused by:
    0: I/O: invalid peer certificate: UnknownIssuer
    1: invalid peer certificate: UnknownIssuer
```
On the server side we get a `[info]  TLS :server: In state :certify received CLIENT ALERT: Fatal - Unknown CA` log

Adding the `--insecure` flag results in a valid TLS handshake and a perfectly functional mqtt session

Adding that info in the doc would be nice, sorry I can't make a PR right now

@EdJoPaTo Thanks for all the good work!
