### ISSUE TITLE
WebUI

### ISSUE THREAD

**Issue by misery** [EdJoPaTo/mqttui#146]
I really like this and use it very often to check something if I am on my desktop. But sometimes I have my smartphone only. Is it possible to provide a WebUI as a daemon? That would be very flexible as it could be hosted on a server. So I could easily check with any device.

**Comment by EdJoPaTo** [comment]
I like the idea (and have thought about something like that) but that would be its own tool. The goal of mqttui is to quickly interact with MQTT via the command line. But yeah, something like that would be awesome!

**Comment by EdJoPaTo** [comment]
I thought about it more and a bunch of stuff needed for something like that is already in mqttui. On the other side: mqttui was never designed to stay open for days which will clearly happen at that point.

Personally I use [Grafana](https://github.com/grafana/grafana), [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics) and my [mqtt2influxdb](https://github.com/EdJoPaTo/mqtt2influxdb) for a dashboard to look into MQTT data.

As I already have that I don't really need a web UI. Without a personal need for something I will probably not implement something like this myself. The idea is still cool!
