### ISSUE TITLE
Redirecting to FIFO makes mqttui fail to connect

### ISSUE THREAD

**Issue by matthiasbeyer** [EdJoPaTo/mqttui#153]
The following snippet illustrates the issue:

```
mkfifo ./foo
mqttui read-one topic > ./foo
```

You can observe (on your broker) that mqttui does not connect to the broker in this case.

Redirecting to a normal file works as expected.

---

Found with @TheNeikos

**Comment by EdJoPaTo** [comment]
Not sure that is the case. Never heard or used `mkfifo` before so I might be off to its usage.
Searched for examples online on how to use it and and commands like echo block until its output can be written to the pipe.

Doing this in two shells seems to work fine:
```bash
mkfifo test
tail --follow test
```

```bash
mqttui read-one topic > test
```

Maybe I dont understand correctly what the use case is which should work but isnt working. Currently it seems like its behaving as other commands doing output?

**Comment by EdJoPaTo** [comment]
I am a bit curious why stuff like connecting doesn’t work. Nothing is put onto the output before so why is it blocking? Can programs be rewritten to not use stdout until they actually want to write something to it? So… is it a shell thing or a „open stdout from process“ thing?

**Comment by matthiasbeyer** [comment]
The shell does not even spawn `mqttui` until it is able to open the fifo (and then hand it to `mqttui`). So there's nothing `mqttui` can do, really ... because it does not run!
