### ISSUE TITLE
not all topics are shown with topic # in treeview

### ISSUE THREAD

**Issue by andree-b** [EdJoPaTo/mqttui#156]
I use mqttui to browse all avaiable topics on my mqtt broker
`mqttui -b mqtt://server "#"`
At least in one nested subtree not all topics are shown, eg in /a/b/c i only see /a/b/c/d1 and /a/b/c/d2 even though there are d1 to d5, but when i open with `mqttui -b mqtt://server "/a/b/#"` all topics are displayed.

Is there a limit of how many topics can be handled by the treeview? Or how deeply nested a topic-tree may be?

**Comment by EdJoPaTo** [comment]
mqttui shouldn't limit anything there.

The first thing that comes to my mind is a limit by the broker. Brokers can limit what they return on certain subscribed topics. For example the `$SYS` topic is normally not returned. Also big online servers usually don't allow subscribing to `#` as it would create a bunch of traffic. Brokers used at home shouldn't do something like this…

Which broker is used there?

Something probably unrelated: a topic starting with a `/` like `/a/b/c` is interpreted as `['', 'a', 'b', 'c']` by the MQTT Specification. The first part is just an empty key then. Normally there shouldn't be a starting `/` when MQTT is used. But its unlikely the cause of the missing topics.

**Comment by andree-b** [comment]
Thanks for pointing me in the right direction, it was indeed a limit of the broker - in my case mosquitto which had max_queued_messages set to 100 in the default ubuntu 20.04 LTS installation i am running.

Changing that value to 1000 (which probably is the current upstream default according to https://mosquitto.org/man/mosquitto-conf-5.html) fixed my problem.

(the leading / was just an error in the description here, i was not using it with the real paths here)
