### ISSUE TITLE
Release filename contains version number making it difficult to automate install of latest version

### ISSUE THREAD

**Issue by ryanwinter** [EdJoPaTo/mqttui#170]
Hey, love your product and use it daily, but I have some automated environments and would like to install the latest version. However with the version as part of the filename, it's difficult to do as I cant just use the `latest` release because I still need to know the latest version number.

Would it be possible to release without the version number in the filename so I can make sure I always run the latest?

**Comment by EdJoPaTo** [comment]
Funny thing: I was also asked the opposite to know what version was downloaded there when looking at downloaded file.

so yeah, possible, not sure what the best way there is.

**Comment by EdJoPaTo** [comment]
In case it helps:

```bash
curl --silent https://api.github.com/repos/EdJoPaTo/mqttui/releases/latest | jq --raw-output .tag_name
```

**Comment by ryanwinter** [comment]
Lol thats so funny, I can say that I'm pretty sure I have requested this from other downloads in the past because it's kind of annoying when you download an installer and then come back a bit later and have no idea what version it is :)

Thanksfor the API call, I can do some parsing to grab the latest from that.
