### ISSUE TITLE
build is presently broken on account of ratatui-binary-data-widget dependency

### ISSUE THREAD

**Issue by froztbyte** [EdJoPaTo/mqttui#173]
heya

currently this fails to build because ratatui-binary-data-widget upstream has changed: 

```
error[E0308]: mismatched types
  --> src/interactive/details/payload_view.rs:88:62
   |
88 |         let max_lines = widget.get_max_lines_of_data_in_area(area);
   |                                ----------------------------- ^^^^ expected `ratatui::layout::rect::Rect`, found `Rect`
   |                                |
   |                                arguments to this method are incorrect
```

setting it to build off [834ab06c030f4069e83b25d39582508fb0faceae](https://github.com/EdJoPaTo/ratatui-binary-data-widget/commits/main/) succeeds

**Comment by EdJoPaTo** [comment]
Yeah. The binary widget is already at ratataui 0.27 but mqttui itself is still at 0.26 as it creates bugs to update (#172).

The build should work when using the lockfile. Cargo run and build do so by default. `cargo install --locked` should apply this to `install`.

When the lockfile is not updated it should be no problem? (At least that's the point of the lockfile.) Or am I overlooking something?

**Comment by EdJoPaTo** [comment]
I reverted that change in `ratatui-binary-data-widget`. Will update both that and mqttui at the same time once https://github.com/ratatui-org/ratatui/pull/1226 is released.
