### ISSUE TITLE
Authorization support?

### ISSUE THREAD

**Issue by sshaikh** [EdJoPaTo/mqttui#18]
Does mqttui support authorisation? I'm trying to connect to an (unencrypted) mosquitto instance:

```
thread 'main' panicked at 'connection error: Io(Custom { kind: InvalidData, error: "Broker rejected. Reason = NotAuthorized" })'
```

**Comment by EdJoPaTo** [comment]
Currently it does not, but it should be possible to add that to the [cli](https://github.com/EdJoPaTo/mqttui/blob/main/src/cli.rs) and the [mqtt options](https://github.com/EdJoPaTo/mqttui/blob/006ae89f1222f928a94c14dcd29b3bb0e126f41d/src/main.rs#L29).

I can take a look on it but I assume its relatively easy for someone willing to provide a PR. I'll happily help with that when someone is willing to try.

**Comment by EdJoPaTo** [comment]
I added support via cli arguments in 1c6e9b87505d97dc132ac99843b5813095a96fe6 but its not released yet. Can you check if it is working as expected?

Either compile the main branch yourself or get the latest build from the CI Artifacts:
https://github.com/EdJoPaTo/mqttui/actions/workflows/rust.yml?query=branch%3Amain

**Comment by EdJoPaTo** [comment]
I tested both the interactive GUI and the publish subcommand with mosquitto requiring auth and both work fine.
This will be part of v0.14.0
