### ISSUE TITLE
Cltr-C ignored when subscribing on CLI

### ISSUE THREAD

**Issue by matthiasbeyer** [EdJoPaTo/mqttui#39]
When running without TUI, `ctrl-c` is ignored.

Example:

```console
mqttui l foo
^c
# process still running
```

---

Thanks for writing this tool, it helped me a lot today! :heart:

**Comment by EdJoPaTo** [comment]
Interesting. I do not seem to be able to reproduce this. `mqttui l foo` followed by Ctrl-C works in both zsh and bash on Arch Linux for me. Not sure what else might influence that.

mqttui does not use special signal handling and so the default "just kill the execution" behaviour is applied. (Only the interactive TUI view does that)
I assume other cli thingies should have the same problem then?

Other ideas how I might be able to recreate your issue?
Also thanks for your kind words and for taking the time of reporting issues you had. It's always nice to hear something I built is also useful for others and what might improve that :)

**Comment by matthiasbeyer** [comment]
> I assume other cli thingies should have the same problem then?

Well "subscribe" is the only thing that waits for external events (does not return immediately), right? So others do not have that effect.

I looked at the code and did not find a cltr-c handler, which makes me curious. Default behaviour should definitively apply here, BUT I guess as you're using `rumqttc`, which spawns background threads, this might be the actual issue! Your code gets stopped with ctrl-c, but the background threads might not get killed ... That's what I thought at least. But if it works for you, I'm having a hard time thinking of something else.

I will continue to observe the issue!

**Comment by EdJoPaTo** [comment]
> Well "subscribe" is the only thing that waits for external events (does not return immediately), right?

`mqttui clean-retained` does something similar but yeah.

As far as I understand the default behaviour it is killing everything relatively strict. And even if the main thread is terminating (break in the main loop) everything gets closed fine.
My go to test for this scenario (for cargo-flamegraph for example) is a timeout:

```diff
+    let begin = Instant::now();
     for notification in connection.iter() {
+        if begin.elapsed().as_secs() > 10 {
+            break;
+        }
```

You can try to compile mqttui yourself, maybe that also changes things but yeah… As you said, there does not seem to be something obvious.

**Comment by EdJoPaTo** [comment]
Personally I don't have this issue and I am not sure how I would be able to reproduce it. No-one else reported something similar in this issue so far.
I think I'll just close it. When this issue comes up again we can open it again.
