### ISSUE TITLE
Support Websocket (ws, and wss)

### ISSUE THREAD

**Issue by YarekTyshchenko** [EdJoPaTo/mqttui#43]
Rust rumqttc does support different transports, but the application doesn't understand mqtt URIs like `wss://broker/ws-path`

**Comment by EdJoPaTo** [comment]
I tried to activate the feature and pass an `ws://` URL. It does not work without setting the Transport to `Transport::Ws`.

A more powerful way of achieving websocket support might be [the url parsing](https://github.com/bytebeamio/rumqtt/blob/2f71df0c49ec22d6e3c830687a2aef1273490e62/rumqttc/src/lib.rs#L391-L409).

But this raises the question on how to handle the CLI for that well.
An idea might be to deprecate/remove the current `--broker`, `--port`, … settings and do everything via the URL. But currently it requires the url to contain the `client_id` which would be annoying for the enduser. Alternatively there could be an URL option which allows for powerful settings while overriding the existing MQTT protocol options.

**Comment by EdJoPaTo** [comment]
Supporting all the ways to contact a broker will require better CLI options and will probably be a breaking change (to the CLI). I would like to wait for https://github.com/bytebeamio/rumqtt/pull/391 before continuing here.

**Comment by EdJoPaTo** [comment]
1de52b1e476ef3cbb4a3966ad252a724b6f7cb9c should introduce websocket support.
Feel free to test it and report back if it could be released like that.

(You can download a prebuilt binary from [here](https://github.com/EdJoPaTo/mqttui/actions/workflows/rust.yml?query=branch%3Amain))

**Comment by YarekTyshchenko** [comment]
Works great!
It might be nice to have an option to specify the username, password, and client id (mainly the client id) via more command line switches. The `ws` protocol actually makes a HTTP request first, so manging that URL is a little confusing.
Overall it works though, so thanks a lot for the patch!

**Comment by EdJoPaTo** [comment]
As the WebSockets are working I think this issue can be closed. The details on how to configure the connection via CLI should be done in a separate discussion (see #70).
When that's figured out the WebSocket support can be released in the next version.

**Comment by EdJoPaTo** [comment]
Thank you for testing @YarekTyshchenko! :blue_heart:
