### ISSUE TITLE
PageUp & PageDown

### ISSUE THREAD

**Issue by misery** [EdJoPaTo/mqttui#49]
Hi!

Thanks for this nice UI. I switched immediately from mqtt-explorer after I found it. :-)

I have a lot of devices in home assistant. So it is a pain to scroll down the whole list. It would help if I could use "page up" and "page down" keys to scroll a whole page at once. Would that be possible?

**Comment by misery** [comment]
Just look into open issues before opening one ;-) #48

**Comment by EdJoPaTo** [comment]
Thanks for the nice words!

As written in the other issue, some absolute numbers like +10/-10 are probably easier than using the height of the current terminal window. But yeah, should be possible and I will look into it (soon :tm:)!

Thanks for bringing up ideas for improvements!
