### ISSUE TITLE
New cpu architecture, ARM64?

### ISSUE THREAD

**Issue by aaronsb** [EdJoPaTo/mqttui#83]
Would it be possible to compile for arm64? I am compiling manually right now so I can run on an 8gb raspberry pi 3b+, and it would be nice to just download latest tested target instead. Sorry I am kind of lazy by asking, let me know if/how you want me to contribute to help.

**Comment by EdJoPaTo** [comment]
Thank your for your interest in this project!

The CI already precompiles for arm64 on macOS and Linux. Its precompiled for arm64 Windows too but without TLS support. Rust names arm64 as `aarch64`.

As you are asking for a Raspberry Pi you are probably interested in this: `aarch64-unknown-linux-gnu`. If you are using the official Raspberry Pi OS (Debian derivat) then you can install the .deb package too (`sudo dpkg -i *.deb`).
Also arm64 runs armv7 and armv6 binaries too so which is neat to know.

I hope this helps!

**Comment by aaronsb** [comment]
Yes it does! I had been using mqttui for a little while and at the time I guess I missed the aarch64 version in releases, thanks! Just to explain how much I didn't see it, I wrote a little cron job to recompile from rust sources every now and then off of main. 😅
